// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: proto/temperature.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemperatureConverterClient is the client API for TemperatureConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemperatureConverterClient interface {
	// Convert Fahrenheit to Celsius
	ConvertToFahrenheit(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
	// Convert Celsius to Fahrenheit
	ConvertToCelsius(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error)
}

type temperatureConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewTemperatureConverterClient(cc grpc.ClientConnInterface) TemperatureConverterClient {
	return &temperatureConverterClient{cc}
}

func (c *temperatureConverterClient) ConvertToFahrenheit(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, "/temperature.TemperatureConverter/ConvertToFahrenheit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temperatureConverterClient) ConvertToCelsius(ctx context.Context, in *TemperatureRequest, opts ...grpc.CallOption) (*TemperatureResponse, error) {
	out := new(TemperatureResponse)
	err := c.cc.Invoke(ctx, "/temperature.TemperatureConverter/ConvertToCelsius", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemperatureConverterServer is the server API for TemperatureConverter service.
// All implementations must embed UnimplementedTemperatureConverterServer
// for forward compatibility
type TemperatureConverterServer interface {
	// Convert Fahrenheit to Celsius
	ConvertToFahrenheit(context.Context, *TemperatureRequest) (*TemperatureResponse, error)
	// Convert Celsius to Fahrenheit
	ConvertToCelsius(context.Context, *TemperatureRequest) (*TemperatureResponse, error)
	mustEmbedUnimplementedTemperatureConverterServer()
}

// UnimplementedTemperatureConverterServer must be embedded to have forward compatible implementations.
type UnimplementedTemperatureConverterServer struct {
}

func (UnimplementedTemperatureConverterServer) ConvertToFahrenheit(context.Context, *TemperatureRequest) (*TemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToFahrenheit not implemented")
}
func (UnimplementedTemperatureConverterServer) ConvertToCelsius(context.Context, *TemperatureRequest) (*TemperatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToCelsius not implemented")
}
func (UnimplementedTemperatureConverterServer) mustEmbedUnimplementedTemperatureConverterServer() {}

// UnsafeTemperatureConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemperatureConverterServer will
// result in compilation errors.
type UnsafeTemperatureConverterServer interface {
	mustEmbedUnimplementedTemperatureConverterServer()
}

func RegisterTemperatureConverterServer(s grpc.ServiceRegistrar, srv TemperatureConverterServer) {
	s.RegisterService(&TemperatureConverter_ServiceDesc, srv)
}

func _TemperatureConverter_ConvertToFahrenheit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertToFahrenheit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temperature.TemperatureConverter/ConvertToFahrenheit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertToFahrenheit(ctx, req.(*TemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemperatureConverter_ConvertToCelsius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemperatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemperatureConverterServer).ConvertToCelsius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temperature.TemperatureConverter/ConvertToCelsius",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemperatureConverterServer).ConvertToCelsius(ctx, req.(*TemperatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemperatureConverter_ServiceDesc is the grpc.ServiceDesc for TemperatureConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemperatureConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temperature.TemperatureConverter",
	HandlerType: (*TemperatureConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToFahrenheit",
			Handler:    _TemperatureConverter_ConvertToFahrenheit_Handler,
		},
		{
			MethodName: "ConvertToCelsius",
			Handler:    _TemperatureConverter_ConvertToCelsius_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/temperature.proto",
}
